# Data Encoding

In [6]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [7]:
myData = pd.read_csv('SeoulBikeData.csv')
data_oneshot = myData.copy()

In [8]:
hotEnc = OneHotEncoder()

features = data_oneshot[['Seasons']]
encoded = hotEnc.fit_transform(features).toarray()

In [9]:
labels = ['Holiday', 'Functioning Day']

for label in labels:
    labelEnc = LabelEncoder()
    labelEnc = labelEnc.fit(data_oneshot[label])
    data_oneshot[label] = labelEnc.transform(data_oneshot[label])

In [10]:
data_oneshot = data_oneshot.drop(columns='Seasons')

hotEnc.get_feature_names_out()

encoded_df = pd.DataFrame(encoded)
encoded_df.columns = hotEnc.get_feature_names_out()

data_oneshot = pd.concat([data_oneshot, encoded_df], axis=1)


data_oneshot.to_csv("SeoulBikeData_Cleaned.csv", index=False)
data_oneshot.head(10)

,Date,Rented Bike Count,Hour,Temperature(C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Holiday,Functioning Day,Seasons_Autumn,Seasons_Spring,Seasons_Summer,Seasons_Winter
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.00,0.0,0.0,1,1,0.0,0.0,0.0,1.0
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.00,0.0,0.0,1,1,0.0,0.0,0.0,1.0
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.00,0.0,0.0,1,1,0.0,0.0,0.0,1.0
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.00,0.0,0.0,1,1,0.0,0.0,0.0,1.0
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.00,0.0,0.0,1,1,0.0,0.0,0.0,1.0
5,01/12/2017,100,5,-6.4,37,1.5,2000,-18.7,0.00,0.0,0.0,1,1,0.0,0.0,0.0,1.0
6,01/12/2017,181,6,-6.6,35,1.3,2000,-19.5,0.00,0.0,0.0,1,1,0.0,0.0,0.0,1.0
7,01/12/2017,460,7,-7.4,38,0.9,2000,-19.3,0.00,0.0,0.0,1,1,0.0,0.0,0.0,1.0
8,01/12/2017,930,8,-7.6,37,1.1,2000,-19.8,0.01,0.0,0.0,1,1,0.0,0.0,0.0,1.0
9,01/12/2017,490,9,-6.5,27,0.5,1928,-22.4,0.23,0.0,0.0,1,1,0.0,0.0,0.0,1.0